### ISSUE TITLE
Packet type 9 not implemented.

### ISSUE THREAD

**Issue by tjorim** [lkempf/casambi-bt-hass#5]
Logger: CasambiBt._client
Source: runner.py:120
First occurred: 12:02:08 AM (4 occurrences)
Last logged: 12:15:48 AM

Packet type 9 not implemented. Ignoring!
Invalid signature for packet b'010a9e000200f2d5654b348c1e8944503ac02a5b983cc8'!

PS: I also notice HA discovering the device again after the integration is already set up.

**Comment by lkempf** [comment]
I know that packet type 9 isn't implemented but I have no idea what that packet does and it doesn't seem to matter all that much.

The invalid signature error seems more serious. Is the integration working for you? If not and to investigate this further I would need additional logs. See the Readme on how to enable them. 

I don't know how to prevent the rediscovery but for me this only happens when I set up the network manually and the network gets discovered afterwards. Just out of interest: Does it discover the same MAC twice or is it two different ones? The latter would mean that your network has two units that can be used for communication, probably because it is bigger.

**Comment by lkempf** [comment]
#7 tracks the case of the same network being discovered twice with different MACs. Is this what you mean by rediscovery?

**Comment by CFenner** [comment]
I my case it is discovered twice with the same MAC. I use 3 equal luminaires that all can also use standalone.

**Comment by tjorim** [comment]
I don't have this issue with the latest version anymore.
